apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: main
spec:
  secretName: tls-cert
  issuerRef:
    name: tls-cert-issuer-high
    kind: ClusterIssuer
  dnsNames:
    - 123myblog.work
    - api.123myblog.work
