version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          name: Updates
          base-revision: << pipeline.git.branch >>
          config-path: .circleci/continue-config.yml
          mapping: |
            api/.* api-service-job true
            frontend/.* frontend-service-job true
      filters: 
        branches:
          only:
            - dev
            - release
            - main
