apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: dev
spec:
  secretName: tls-cert
  issuerRef:
    name: tls-cert-issuer-low
    kind: ClusterIssuer
  dnsNames:
    - dev.123myblog.work
    - dev-api.123myblog.work
