apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: main
data:
  PORT: "4000"
  CURRENT_ENV: "main"
  MEZMO_KEY: "ab22ce064545bd8978e8804ead844000"
  GOOGLE_EMAIL: "oselqtwinalkjvui"
  GOOGLE_KEY: "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"
  JWT_KEY: "super_secret_key"
