apiVersion: v1
kind: Service
metadata:
  name: blogapp-frontend
  namespace: dev
  labels:
    k8s-app: blogapp-frontend
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      name: http
      targetPort: 3000
  selector:
    k8s-app: blogapp-frontend
---

