apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tls-cert-issuer-low
  namespace: cert-manager
spec:
  acme:
    email: enverov.ametkhan@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
    privateKeySecretRef:
      name: tls-cert-issuer-low
    solvers:
      - dns01:
          cloudflare:
            email: enverov.ametkhan@gmail.com
            apiKeySecretRef:
              name: cloudflare-api-key
              key: api-key

---

