apiVersion: v1
kind: Service
metadata:
  name: blogapp-backend
  namespace: release
  labels:
    k8s-app: blogapp-backend
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4000
      name: http
      targetPort: 4000
  selector:
    k8s-app: blogapp-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: release
  annotations:
    keel.sh/pollSchedule: "@every 1m"
    # keel.sh/notify: SLACK_CHANNEL

    description: blogapp-backend
  generation: 1
  labels:
    keel.sh/policy: force # update policy (available: patch, minor, major, all, force)
    keel.sh/trigger: poll # enable active repository checking (webhooks and GCR would still work)
    keel.sh/approvals: "0" # required approvals to update
    keel.sh/match-tag: "true" #
    # keel.sh/notify: SLACK_CHANNEL
    k8s-app: blogapp-backend
  name: blogapp-backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: blogapp-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: blogapp-backend
      labels:
        k8s-app: blogapp-backend
      name: blogapp-backend
    spec:
      containers:
        - image: gcr.io/capable-reserve-410215/api/release
          imagePullPolicy: Always
          name: blogapp-backend
          envFrom:
            - configMapRef:
                name: backend-configmap
          # resources:
          #   limits:
          #     memory: 300Mi
          #     cpu: 100m
          #   requests:
          #     memory: 300Mi
          #     cpu: 100m
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
            - containerPort: 4000

      imagePullSecrets:
        - name: gcr-access-account
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
status: {}
